### ISSUE TITLE
没有distinct功能

### ISSUE THREAD

**Issue by lljxww** [ThinkerCodeChina/jsonDB#1]
业务需要distinct功能,暂时用另一张表去单独存储的.由于本人能力有限,不能一起contribute.悲伤ing

**Comment by thinkeridea** [comment]
抱歉事情很多，并没有跟进你的问题，我想这只是一个简单的json查询器，实现distinct虽然可行，但是损失一些性能，建议是自己处理一下，实际上这样的功能在已经查找的结果里去重非常的简单
